//app/[locale]/school/layout.tsx
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "../../globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div lang="en">
      <div>{children}</div>
    </div>
  );
}
